from flask import Flask, request, jsonify, request
import sqlite3

app = Flask(__name__)

@app.route('/')
def index():
    return app.send_static_file('index.html')

# Helper function to connect to the database
def get_db_connection():
    conn = sqlite3.connect('orders.db')
    conn.row_factory = sqlite3.Row # Returns rows as dictionaries instead of tuples
    return conn

# 1. Endpoint to send the menu to the frontend
@app.route('/api/products', methods=['GET'])
def get_products():
    conn = get_db_connection()
    products = conn.execute('SELECT * FROM products').fetchall()
    conn.close()
    
    # Convert rows to standard Python dictionaries
    return jsonify([dict(row) for row in products])

# 2. Endpoint to process the checkout
@app.route('/api/orders', methods=['POST'])
def place_order():
    data = request.get_json()
    customer_name = data.get('name')
    cart_items = data.get('cart') # Example: [{"product_id": 1, "qty": 2}]

    if not customer_name or not cart_items:
        return jsonify({'error': 'Missing name or cart data'}), 400

    conn = get_db_connection()
    cursor = conn.cursor()

    try:
        total_price = 0
        
        # Step A: Verify stock and calculate the REAL price based on the database
        for item in cart_items:
            product = cursor.execute('SELECT * FROM products WHERE id = ?', (item['product_id'],)).fetchone()
            
            if not product:
                return jsonify({'error': f"Product ID {item['product_id']} not found"}), 404
            if product['stock'] < item['qty']:
                return jsonify({'error': f"Not enough stock for {product['name']}"}), 400
            
            total_price += product['price'] * item['qty']

        # Step B: Create the overall order
        cursor.execute('INSERT INTO orders (customer_name, total_price) VALUES (?, ?)', 
                       (customer_name, total_price))
        order_id = cursor.lastrowid # Grabs the new ID generated by SQLite

        # Step C: Save individual items and deduct from stock
        for item in cart_items:
            product = cursor.execute('SELECT * FROM products WHERE id = ?', (item['product_id'],)).fetchone()
            
            cursor.execute('''
                INSERT INTO order_items (order_id, product_id, qty, price_at_purchase) 
                VALUES (?, ?, ?, ?)
            ''', (order_id, item['product_id'], item['qty'], product['price']))
            
            cursor.execute('UPDATE products SET stock = stock - ? WHERE id = ?', 
                           (item['qty'], item['product_id']))

        # Commit the transaction so all changes save at once
        conn.commit()
        return jsonify({'message': 'Order placed successfully!', 'order_id': order_id}), 201

    except Exception as e:
        # If anything fails (like a database error), cancel the whole transaction
        conn.rollback()
        return jsonify({'error': str(e)}), 500
    finally:
        conn.close()

if __name__ == '__main__':
    app.run(debug=True)